#!/bin/bash

# Check if two arguments are provided
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <file_path> <param>"
    exit 1
fi

# Assign parameters to variables
FILE_PATH="$1"
PARAM="$2"

# Run the make command with the provided arguments
make run ARGS="$FILE_PATH $PARAM"
